Custom Input Tags Widget w/ Tag editing and color display
wbreza/vott-react-typescript pull request #13
Opened 2018-12-01 03:56 UTC by tbarlow12

2018-12-05 18:08 UTC, wbreza requested changes

2018-12-05 18:08 UTC, wbreza commented on src/react/components/common/tagsInput/tagsInput.tsx
> +        if (text === undefined) {
Can be simplified to `if(!text)`

2018-12-05 18:08 UTC, wbreza commented on src/react/components/common/tagsInput/tagsInput.tsx
> +        const result = JSON.stringify(tags.map((element) => (({ id, color }) => ({ id, color }))(element)));
We need to store the tags as an actual object vs. stringified JSON.

2018-12-05 18:08 UTC, wbreza commented on src/react/components/common/tagsInput/tagEditorModal/tagEditorModal.json
> +                "white", "silver", "gray", "red", "maroon", "yellow", "olive",
We should store the tags colors as hex values to support user defined input.

2018-12-05 18:08 UTC, wbreza commented on src/react/components/common/tagsInput/tagsInput.test.tsx
> +            color: "blue",
Let's use hex colors

2018-12-05 18:08 UTC, wbreza commented on src/react/components/common/tagsInput/tagsInput.tsx
> +            tagsCopy = JSON.parse(JSON.stringify(props.tags));
OK - i think i know why you are doing this - because you are storing it as actual JSON string.  Once you fix the storage side you shouldn't need to do this dance.

2018-12-05 21:36 UTC, tbarlow12 commented on src/react/components/common/tagsInput/tagsInput.test.tsx
> +            expect(stateTags[i].id).toEqual(originalTags[i].id);
good catch. forgot the `[i]`

2018-12-06 14:55 UTC, tbarlow12 commented on src/react/components/common/tagsInput/tagsInput.tsx
> +        const result = JSON.stringify(tags.map((element) => (({ id, color }) => ({ id, color }))(element)));
I agree, and that's been my goal from the beginning. This has been my workaround for the `react-jsonschema-form` package due to not being able to find a way to specify `object` or `array` as the type in the schema while still providing a custom `ui:widget`. Poked at it for a few hours and went back to the workaround. Definitely would love to make the switch if you have any ideas

2018-12-06 18:52 UTC, wbreza commented on src/react/components/common/tagsInput/tagsInput.scss
> +    font-size: 20px;
Instead of using absolute font sizes I would use relative sizing like percentages or em's.  Works best for browser scaling.  Want something smaller than normal body font: consider 80%, bigger, 120%.  Play around with the values and see what works.

2018-12-06 18:53 UTC, wbreza approved these changes
Thanks for addressing the feedback.

2018-12-06 19:36 UTC, tbarlow12 commented on src/react/components/common/tagsInput/tagsInput.scss
> +    font-size: 20px;
Will do. I'd like to keep it consistent with the other project settings input values. I'll look and see what they're using

2018-12-06 20:04 UTC, merged